"""
Django settings for llime project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.expanduser('~/prj/grove/lib'))
MEDIAVIEW_LABEL = 'hty7'
IMHANDLER_VARIANT = 'hty7'
DOCUMENT_VIEWER_VARIANT = 'hty7'

import llemon_djview as _llemon_djview
globals().update(_llemon_djview.django_settings('hty7'))

SITE_NAME = 'Zorf Llime'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%v*ol%w@^%9g@frqq&q7%*u@pf*=5h_^if#xj+0a#i(q9u#^!b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

USE_X_FORWARDED_HOST = True
FORCE_SCRIPT_NAME = '/zorf/llime'
ALLOWED_HOSTS = [
    'www.myzorf.com',
    'localhost'
]

CSRF_TRUSTED_ORIGINS = [
    'https://www.myzorf.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'llemon_djview',
    'imhandler.djview',
    'base',
    'to_do_list',
    'mediaview',
    'documentview',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.site_name',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Pacific/Honolulu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/zorf/llime/static/'

# documentview -- see ../../lib/documentview/CLAUDE.md.
# DOCUMENT_VIEWER_ROOT / DOCUMENT_VIEWER_EXPORTS_DIR are configured in
# ../../etc/documentview.conf (variant selected by DOCUMENT_VIEWER_VARIANT
# above), not here -- see that file to change them.
DOCUMENT_VIEWER_STYLESHEET_URL = '/zorf/llime/static/base/css/documentview.css'


def _authorize_document_viewer(request, action):
    """Llime is authenticated by the web server, outside Django."""
    return True


DOCUMENT_VIEWER_AUTHORIZE = _authorize_document_viewer


def _authorize_imhandler_blacklist(request):
    """Same reasoning as _authorize_document_viewer: llime is authenticated
    by the web server, outside Django. Wrapped rather than assigned
    directly because that hook takes (request, action) and this one is
    called with (request) alone."""
    return _authorize_document_viewer(request, 'blacklist')


IMHANDLER_BLACKLIST_AUTHORIZER = _authorize_imhandler_blacklist

_log_dir = LLEMON_LOG_DIR
if _log_dir:
    from datetime import datetime as _datetime
    os.makedirs(_log_dir, exist_ok=True)
    _log_file = os.path.join(_log_dir, f'trace-{_datetime.now().strftime("%Y%m%d-%H%M%S")}.log')
    _file_handlers = {'hty7_file': {'class': 'logging.FileHandler', 'filename': _log_file, 'formatter': 'hty7'}}
    _hty7_logger = {'hty7': {'handlers': ['hty7_file'], 'level': 'DEBUG', 'propagate': False}}
else:
    _file_handlers = {}
    _hty7_logger = {}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'hty7': {'format': '%(asctime)s %(levelname)-8s %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
        **_file_handlers,
    },
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        **_hty7_logger,
        'llemon': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False},
    },
}
